// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest sent by agent during initial registration
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	MacAddress    string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	OsType        string                 `protobuf:"bytes,5,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	OsVersion     string                 `protobuf:"bytes,6,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Architecture  string                 `protobuf:"bytes,7,opt,name=architecture,proto3" json:"architecture,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,8,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterRequest) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *RegisterRequest) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *RegisterRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegisterRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RegisterResponse sent by control plane after successful registration
type RegisterResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Success                  bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NodeId                   string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Message                  string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,4,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	Config                   map[string]string      `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *RegisterResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// HeartbeatRequest sent periodically by agent
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // online, degraded, shutting_down
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       *SystemMetrics         `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	ActiveTasks   int32                  `protobuf:"varint,6,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HeartbeatRequest) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

// HeartbeatResponse acknowledges heartbeat
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ConfigUpdates map[string]string      `protobuf:"bytes,2,rep,name=config_updates,json=configUpdates,proto3" json:"config_updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PendingTasks  []*Task                `protobuf:"bytes,3,rep,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"` // Tasks to be executed by agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetConfigUpdates() map[string]string {
	if x != nil {
		return x.ConfigUpdates
	}
	return nil
}

func (x *HeartbeatResponse) GetPendingTasks() []*Task {
	if x != nil {
		return x.PendingTasks
	}
	return nil
}

// TaskMessage used for bidirectional task streaming
type TaskMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*TaskMessage_Task
	//	*TaskMessage_Result
	//	*TaskMessage_Ack
	Message       isTaskMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMessage) Reset() {
	*x = TaskMessage{}
	mi := &file_api_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMessage) ProtoMessage() {}

func (x *TaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMessage.ProtoReflect.Descriptor instead.
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *TaskMessage) GetMessage() isTaskMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TaskMessage) GetTask() *Task {
	if x != nil {
		if x, ok := x.Message.(*TaskMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *TaskMessage) GetResult() *TaskResult {
	if x != nil {
		if x, ok := x.Message.(*TaskMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *TaskMessage) GetAck() *TaskAck {
	if x != nil {
		if x, ok := x.Message.(*TaskMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isTaskMessage_Message interface {
	isTaskMessage_Message()
}

type TaskMessage_Task struct {
	Task *Task `protobuf:"bytes,1,opt,name=task,proto3,oneof"`
}

type TaskMessage_Result struct {
	Result *TaskResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type TaskMessage_Ack struct {
	Ack *TaskAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*TaskMessage_Task) isTaskMessage_Message() {}

func (*TaskMessage_Result) isTaskMessage_Message() {}

func (*TaskMessage_Ack) isTaskMessage_Message() {}

// Task represents work to be executed by agent
type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId          string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // command, script, file, firmware, etc.
	Command        string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Script         string                 `protobuf:"bytes,5,opt,name=script,proto3" json:"script,omitempty"`
	Parameters     map[string]string      `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority       int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,9,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *Task) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Task) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// TaskResult sent by agent after task execution
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DurationMs    int64                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_api_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *TaskResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TaskResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TaskResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TaskAck acknowledges task receipt
type TaskAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Received      bool                   `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAck) Reset() {
	*x = TaskAck{}
	mi := &file_api_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAck) ProtoMessage() {}

func (x *TaskAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAck.ProtoReflect.Descriptor instead.
func (*TaskAck) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TaskAck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *TaskAck) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// SystemMetrics contains system health metrics
type SystemMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,2,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	DiskPercent   float64                `protobuf:"fixed64,3,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	LoadAvg_1M    float64                `protobuf:"fixed64,4,opt,name=load_avg_1m,json=loadAvg1m,proto3" json:"load_avg_1m,omitempty"`
	LoadAvg_5M    float64                `protobuf:"fixed64,5,opt,name=load_avg_5m,json=loadAvg5m,proto3" json:"load_avg_5m,omitempty"`
	LoadAvg_15M   float64                `protobuf:"fixed64,6,opt,name=load_avg_15m,json=loadAvg15m,proto3" json:"load_avg_15m,omitempty"`
	UptimeSeconds uint64                 `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_api_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SystemMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemMetrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *SystemMetrics) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *SystemMetrics) GetLoadAvg_1M() float64 {
	if x != nil {
		return x.LoadAvg_1M
	}
	return 0
}

func (x *SystemMetrics) GetLoadAvg_5M() float64 {
	if x != nil {
		return x.LoadAvg_5M
	}
	return 0
}

func (x *SystemMetrics) GetLoadAvg_15M() float64 {
	if x != nil {
		return x.LoadAvg_15M
	}
	return 0
}

func (x *SystemMetrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// MetricsRequest contains detailed metrics
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	System        *SystemMetrics         `protobuf:"bytes,3,opt,name=system,proto3" json:"system,omitempty"`
	Processes     []*ProcessMetrics      `protobuf:"bytes,4,rep,name=processes,proto3" json:"processes,omitempty"`
	Disks         []*DiskMetrics         `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	Network       []*NetworkMetrics      `protobuf:"bytes,6,rep,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *MetricsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MetricsRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricsRequest) GetSystem() *SystemMetrics {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *MetricsRequest) GetProcesses() []*ProcessMetrics {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *MetricsRequest) GetDisks() []*DiskMetrics {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *MetricsRequest) GetNetwork() []*NetworkMetrics {
	if x != nil {
		return x.Network
	}
	return nil
}

// ProcessMetrics contains per-process metrics
type ProcessMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMetrics) Reset() {
	*x = ProcessMetrics{}
	mi := &file_api_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMetrics) ProtoMessage() {}

func (x *ProcessMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMetrics.ProtoReflect.Descriptor instead.
func (*ProcessMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessMetrics) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessMetrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ProcessMetrics) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// DiskMetrics contains disk usage metrics
type DiskMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	MountPoint    string                 `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,4,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,5,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	Percent       float64                `protobuf:"fixed64,6,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_api_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DiskMetrics) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskMetrics) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskMetrics) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskMetrics) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskMetrics) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *DiskMetrics) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

// NetworkMetrics contains network statistics
type NetworkMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     uint64                 `protobuf:"varint,3,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	PacketsSent   uint64                 `protobuf:"varint,4,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsRecv   uint64                 `protobuf:"varint,5,opt,name=packets_recv,json=packetsRecv,proto3" json:"packets_recv,omitempty"`
	ErrorsIn      uint64                 `protobuf:"varint,6,opt,name=errors_in,json=errorsIn,proto3" json:"errors_in,omitempty"`
	ErrorsOut     uint64                 `protobuf:"varint,7,opt,name=errors_out,json=errorsOut,proto3" json:"errors_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_api_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *NetworkMetrics) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *NetworkMetrics) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetworkMetrics) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *NetworkMetrics) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *NetworkMetrics) GetPacketsRecv() uint64 {
	if x != nil {
		return x.PacketsRecv
	}
	return 0
}

func (x *NetworkMetrics) GetErrorsIn() uint64 {
	if x != nil {
		return x.ErrorsIn
	}
	return 0
}

func (x *NetworkMetrics) GetErrorsOut() uint64 {
	if x != nil {
		return x.ErrorsOut
	}
	return 0
}

// MetricsResponse acknowledges metrics receipt
type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *MetricsResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// DisconnectRequest sent before agent shutdown
type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *DisconnectRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DisconnectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// DisconnectResponse acknowledges disconnect
type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *DisconnectResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// TaskResultResponse acknowledges task result receipt
type TaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultResponse) Reset() {
	*x = TaskResultResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultResponse) ProtoMessage() {}

func (x *TaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultResponse.ProtoReflect.Descriptor instead.
func (*TaskResultResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *TaskResultResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *TaskResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_agent_proto protoreflect.FileDescriptor

const file_api_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/agent.proto\x12\freignx.agent\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x04\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\x12\x17\n" +
	"\aos_type\x18\x05 \x01(\tR\x06osType\x12\x1d\n" +
	"\n" +
	"os_version\x18\x06 \x01(\tR\tosVersion\x12\"\n" +
	"\farchitecture\x18\a \x01(\tR\farchitecture\x12#\n" +
	"\ragent_version\x18\b \x01(\tR\fagentVersion\x12;\n" +
	"\x04tags\x18\t \x03(\v2'.reignx.agent.RegisterRequest.TagsEntryR\x04tags\x12G\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2+.reignx.agent.RegisterRequest.MetadataEntryR\bmetadata\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x02\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x04 \x01(\x05R\x18heartbeatIntervalSeconds\x12B\n" +
	"\x06config\x18\x05 \x03(\v2*.reignx.agent.RegisterResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfc\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\ametrics\x18\x05 \x01(\v2\x1b.reignx.agent.SystemMetricsR\ametrics\x12!\n" +
	"\factive_tasks\x18\x06 \x01(\x05R\vactiveTasks\"\x8d\x02\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12Y\n" +
	"\x0econfig_updates\x18\x02 \x03(\v22.reignx.agent.HeartbeatResponse.ConfigUpdatesEntryR\rconfigUpdates\x127\n" +
	"\rpending_tasks\x18\x03 \x03(\v2\x12.reignx.agent.TaskR\fpendingTasks\x1a@\n" +
	"\x12ConfigUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\vTaskMessage\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x12.reignx.agent.TaskH\x00R\x04task\x122\n" +
	"\x06result\x18\x02 \x01(\v2\x18.reignx.agent.TaskResultH\x00R\x06result\x12)\n" +
	"\x03ack\x18\x03 \x01(\v2\x15.reignx.agent.TaskAckH\x00R\x03ackB\t\n" +
	"\amessage\"\x97\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x16\n" +
	"\x06script\x18\x05 \x01(\tR\x06script\x12B\n" +
	"\n" +
	"parameters\x18\x06 \x03(\v2\".reignx.agent.Task.ParametersEntryR\n" +
	"parameters\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vmax_retries\x18\t \x01(\x05R\n" +
	"maxRetries\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x03\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\x12B\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2&.reignx.agent.TaskResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\aTaskAck\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\bR\breceived\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x83\x02\n" +
	"\rSystemMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x02 \x01(\x01R\rmemoryPercent\x12!\n" +
	"\fdisk_percent\x18\x03 \x01(\x01R\vdiskPercent\x12\x1e\n" +
	"\vload_avg_1m\x18\x04 \x01(\x01R\tloadAvg1m\x12\x1e\n" +
	"\vload_avg_5m\x18\x05 \x01(\x01R\tloadAvg5m\x12 \n" +
	"\fload_avg_15m\x18\x06 \x01(\x01R\n" +
	"loadAvg15m\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x04R\ruptimeSeconds\"\xbd\x02\n" +
	"\x0eMetricsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\x06system\x18\x03 \x01(\v2\x1b.reignx.agent.SystemMetricsR\x06system\x12:\n" +
	"\tprocesses\x18\x04 \x03(\v2\x1c.reignx.agent.ProcessMetricsR\tprocesses\x12/\n" +
	"\x05disks\x18\x05 \x03(\v2\x19.reignx.agent.DiskMetricsR\x05disks\x126\n" +
	"\anetwork\x18\x06 \x03(\v2\x1c.reignx.agent.NetworkMetricsR\anetwork\"\x96\x01\n" +
	"\x0eProcessMetrics\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01R\rmemoryPercent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xbf\x01\n" +
	"\vDiskMetrics\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1f\n" +
	"\vmount_point\x18\x02 \x01(\tR\n" +
	"mountPoint\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x04 \x01(\x04R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x05 \x01(\x04R\tfreeBytes\x12\x18\n" +
	"\apercent\x18\x06 \x01(\x01R\apercent\"\xee\x01\n" +
	"\x0eNetworkMetrics\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x04R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x03 \x01(\x04R\tbytesRecv\x12!\n" +
	"\fpackets_sent\x18\x04 \x01(\x04R\vpacketsSent\x12!\n" +
	"\fpackets_recv\x18\x05 \x01(\x04R\vpacketsRecv\x12\x1b\n" +
	"\terrors_in\x18\x06 \x01(\x04R\berrorsIn\x12\x1d\n" +
	"\n" +
	"errors_out\x18\a \x01(\x04R\terrorsOut\"5\n" +
	"\x0fMetricsResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"D\n" +
	"\x11DisconnectRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"8\n" +
	"\x12DisconnectResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"R\n" +
	"\x12TaskResultResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xdf\x03\n" +
	"\fAgentService\x12I\n" +
	"\bRegister\x12\x1d.reignx.agent.RegisterRequest\x1a\x1e.reignx.agent.RegisterResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.reignx.agent.HeartbeatRequest\x1a\x1f.reignx.agent.HeartbeatResponse\x12G\n" +
	"\vStreamTasks\x12\x19.reignx.agent.TaskMessage\x1a\x19.reignx.agent.TaskMessage(\x010\x01\x12L\n" +
	"\rReportMetrics\x12\x1c.reignx.agent.MetricsRequest\x1a\x1d.reignx.agent.MetricsResponse\x12O\n" +
	"\n" +
	"Disconnect\x12\x1f.reignx.agent.DisconnectRequest\x1a .reignx.agent.DisconnectResponse\x12N\n" +
	"\x10ReportTaskResult\x12\x18.reignx.agent.TaskResult\x1a .reignx.agent.TaskResultResponseB0Z.github.com/reignx/reignx/api/proto/gen;agentpbb\x06proto3"

var (
	file_api_proto_agent_proto_rawDescOnce sync.Once
	file_api_proto_agent_proto_rawDescData []byte
)

func file_api_proto_agent_proto_rawDescGZIP() []byte {
	file_api_proto_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)))
	})
	return file_api_proto_agent_proto_rawDescData
}

var file_api_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: reignx.agent.RegisterRequest
	(*RegisterResponse)(nil),      // 1: reignx.agent.RegisterResponse
	(*HeartbeatRequest)(nil),      // 2: reignx.agent.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 3: reignx.agent.HeartbeatResponse
	(*TaskMessage)(nil),           // 4: reignx.agent.TaskMessage
	(*Task)(nil),                  // 5: reignx.agent.Task
	(*TaskResult)(nil),            // 6: reignx.agent.TaskResult
	(*TaskAck)(nil),               // 7: reignx.agent.TaskAck
	(*SystemMetrics)(nil),         // 8: reignx.agent.SystemMetrics
	(*MetricsRequest)(nil),        // 9: reignx.agent.MetricsRequest
	(*ProcessMetrics)(nil),        // 10: reignx.agent.ProcessMetrics
	(*DiskMetrics)(nil),           // 11: reignx.agent.DiskMetrics
	(*NetworkMetrics)(nil),        // 12: reignx.agent.NetworkMetrics
	(*MetricsResponse)(nil),       // 13: reignx.agent.MetricsResponse
	(*DisconnectRequest)(nil),     // 14: reignx.agent.DisconnectRequest
	(*DisconnectResponse)(nil),    // 15: reignx.agent.DisconnectResponse
	(*TaskResultResponse)(nil),    // 16: reignx.agent.TaskResultResponse
	nil,                           // 17: reignx.agent.RegisterRequest.TagsEntry
	nil,                           // 18: reignx.agent.RegisterRequest.MetadataEntry
	nil,                           // 19: reignx.agent.RegisterResponse.ConfigEntry
	nil,                           // 20: reignx.agent.HeartbeatResponse.ConfigUpdatesEntry
	nil,                           // 21: reignx.agent.Task.ParametersEntry
	nil,                           // 22: reignx.agent.TaskResult.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 23: google.protobuf.Timestamp
}
var file_api_proto_agent_proto_depIdxs = []int32{
	17, // 0: reignx.agent.RegisterRequest.tags:type_name -> reignx.agent.RegisterRequest.TagsEntry
	18, // 1: reignx.agent.RegisterRequest.metadata:type_name -> reignx.agent.RegisterRequest.MetadataEntry
	19, // 2: reignx.agent.RegisterResponse.config:type_name -> reignx.agent.RegisterResponse.ConfigEntry
	23, // 3: reignx.agent.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 4: reignx.agent.HeartbeatRequest.metrics:type_name -> reignx.agent.SystemMetrics
	20, // 5: reignx.agent.HeartbeatResponse.config_updates:type_name -> reignx.agent.HeartbeatResponse.ConfigUpdatesEntry
	5,  // 6: reignx.agent.HeartbeatResponse.pending_tasks:type_name -> reignx.agent.Task
	5,  // 7: reignx.agent.TaskMessage.task:type_name -> reignx.agent.Task
	6,  // 8: reignx.agent.TaskMessage.result:type_name -> reignx.agent.TaskResult
	7,  // 9: reignx.agent.TaskMessage.ack:type_name -> reignx.agent.TaskAck
	21, // 10: reignx.agent.Task.parameters:type_name -> reignx.agent.Task.ParametersEntry
	23, // 11: reignx.agent.Task.created_at:type_name -> google.protobuf.Timestamp
	23, // 12: reignx.agent.TaskResult.started_at:type_name -> google.protobuf.Timestamp
	23, // 13: reignx.agent.TaskResult.completed_at:type_name -> google.protobuf.Timestamp
	22, // 14: reignx.agent.TaskResult.metadata:type_name -> reignx.agent.TaskResult.MetadataEntry
	23, // 15: reignx.agent.TaskAck.timestamp:type_name -> google.protobuf.Timestamp
	23, // 16: reignx.agent.MetricsRequest.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 17: reignx.agent.MetricsRequest.system:type_name -> reignx.agent.SystemMetrics
	10, // 18: reignx.agent.MetricsRequest.processes:type_name -> reignx.agent.ProcessMetrics
	11, // 19: reignx.agent.MetricsRequest.disks:type_name -> reignx.agent.DiskMetrics
	12, // 20: reignx.agent.MetricsRequest.network:type_name -> reignx.agent.NetworkMetrics
	0,  // 21: reignx.agent.AgentService.Register:input_type -> reignx.agent.RegisterRequest
	2,  // 22: reignx.agent.AgentService.Heartbeat:input_type -> reignx.agent.HeartbeatRequest
	4,  // 23: reignx.agent.AgentService.StreamTasks:input_type -> reignx.agent.TaskMessage
	9,  // 24: reignx.agent.AgentService.ReportMetrics:input_type -> reignx.agent.MetricsRequest
	14, // 25: reignx.agent.AgentService.Disconnect:input_type -> reignx.agent.DisconnectRequest
	6,  // 26: reignx.agent.AgentService.ReportTaskResult:input_type -> reignx.agent.TaskResult
	1,  // 27: reignx.agent.AgentService.Register:output_type -> reignx.agent.RegisterResponse
	3,  // 28: reignx.agent.AgentService.Heartbeat:output_type -> reignx.agent.HeartbeatResponse
	4,  // 29: reignx.agent.AgentService.StreamTasks:output_type -> reignx.agent.TaskMessage
	13, // 30: reignx.agent.AgentService.ReportMetrics:output_type -> reignx.agent.MetricsResponse
	15, // 31: reignx.agent.AgentService.Disconnect:output_type -> reignx.agent.DisconnectResponse
	16, // 32: reignx.agent.AgentService.ReportTaskResult:output_type -> reignx.agent.TaskResultResponse
	27, // [27:33] is the sub-list for method output_type
	21, // [21:27] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_proto_agent_proto_init() }
func file_api_proto_agent_proto_init() {
	if File_api_proto_agent_proto != nil {
		return
	}
	file_api_proto_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*TaskMessage_Task)(nil),
		(*TaskMessage_Result)(nil),
		(*TaskMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_proto_msgTypes,
	}.Build()
	File_api_proto_agent_proto = out.File
	file_api_proto_agent_proto_goTypes = nil
	file_api_proto_agent_proto_depIdxs = nil
}
